//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MikroPic.EdaTools.v1.MouserSearchApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.mouser.com/service", ConfigurationName="MouserSearchApi.SearchAPISoap")]
    public interface SearchAPISoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje SearchByKeywordRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/SearchByKeyword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordResponse SearchByKeyword(MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje SearchByPartNumberRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/SearchByPartNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberResponse SearchByPartNumber(MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje CalculatorRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/Calculator", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MikroPic.EdaTools.v1.MouserSearchApi.CalculatorResponse Calculator(MikroPic.EdaTools.v1.MouserSearchApi.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.mouser.com/service/ServiceStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceStatus();
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AccountInfo accountInfoField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccountInfo AccountInfo {
            get {
                return this.accountInfoField;
            }
            set {
                this.accountInfoField = value;
                this.RaisePropertyChanged("AccountInfo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class AccountInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partnerIDField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MCalculator : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MCalculatorMethod calculatorMethodNameField;
        
        private string resistanceField;
        
        private string toleranceField;
        
        private string temperatureCoefficientField;
        
        private string capacitanceField;
        
        private string inductanceField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MCalculatorMethod CalculatorMethodName {
            get {
                return this.calculatorMethodNameField;
            }
            set {
                this.calculatorMethodNameField = value;
                this.RaisePropertyChanged("CalculatorMethodName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Resistance {
            get {
                return this.resistanceField;
            }
            set {
                this.resistanceField = value;
                this.RaisePropertyChanged("Resistance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
                this.RaisePropertyChanged("Tolerance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TemperatureCoefficient {
            get {
                return this.temperatureCoefficientField;
            }
            set {
                this.temperatureCoefficientField = value;
                this.RaisePropertyChanged("TemperatureCoefficient");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Capacitance {
            get {
                return this.capacitanceField;
            }
            set {
                this.capacitanceField = value;
                this.RaisePropertyChanged("Capacitance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Inductance {
            get {
                return this.inductanceField;
            }
            set {
                this.inductanceField = value;
                this.RaisePropertyChanged("Inductance");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public enum MCalculatorMethod {
        
        /// <comentarios/>
        None,
        
        /// <comentarios/>
        ResistanceCode,
        
        /// <comentarios/>
        ResistanceColorCode1,
        
        /// <comentarios/>
        ResistanceColorCode2,
        
        /// <comentarios/>
        CapacitorCode,
        
        /// <comentarios/>
        Inductance,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class UnitWeightKg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> unitWeightField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> UnitWeight {
            get {
                return this.unitWeightField;
            }
            set {
                this.unitWeightField = value;
                this.RaisePropertyChanged("UnitWeight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pricebreaks2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class Pricebreaks : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int quantityField;
        
        private string priceField;
        
        private string currencyField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class Pricebreaks2 : Pricebreaks {
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class ProductAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttributeName {
            get {
                return this.attributeNameField;
            }
            set {
                this.attributeNameField = value;
                this.RaisePropertyChanged("AttributeName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
                this.RaisePropertyChanged("AttributeValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class MouserPart : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string availabilityField;
        
        private string dataSheetUrlField;
        
        private string descriptionField;
        
        private string imagePathField;
        
        private string categoryField;
        
        private string leadTimeField;
        
        private string lifecycleStatusField;
        
        private string manufacturerField;
        
        private string manufacturerPartNumberField;
        
        private string minField;
        
        private string multField;
        
        private string mouserPartNumberField;
        
        private ProductAttribute[] productAttributesField;
        
        private Pricebreaks[] priceBreaksField;
        
        private string productDetailUrlField;
        
        private bool reelingField;
        
        private string rOHSStatusField;
        
        private string suggestedReplacementField;
        
        private int multiSimBlueField;
        
        private UnitWeightKg unitWeightKgField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
                this.RaisePropertyChanged("Availability");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DataSheetUrl {
            get {
                return this.dataSheetUrlField;
            }
            set {
                this.dataSheetUrlField = value;
                this.RaisePropertyChanged("DataSheetUrl");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
                this.RaisePropertyChanged("ImagePath");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("Category");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LeadTime {
            get {
                return this.leadTimeField;
            }
            set {
                this.leadTimeField = value;
                this.RaisePropertyChanged("LeadTime");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LifecycleStatus {
            get {
                return this.lifecycleStatusField;
            }
            set {
                this.lifecycleStatusField = value;
                this.RaisePropertyChanged("LifecycleStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ManufacturerPartNumber {
            get {
                return this.manufacturerPartNumberField;
            }
            set {
                this.manufacturerPartNumberField = value;
                this.RaisePropertyChanged("ManufacturerPartNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("Min");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Mult {
            get {
                return this.multField;
            }
            set {
                this.multField = value;
                this.RaisePropertyChanged("Mult");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MouserPartNumber {
            get {
                return this.mouserPartNumberField;
            }
            set {
                this.mouserPartNumberField = value;
                this.RaisePropertyChanged("MouserPartNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public ProductAttribute[] ProductAttributes {
            get {
                return this.productAttributesField;
            }
            set {
                this.productAttributesField = value;
                this.RaisePropertyChanged("ProductAttributes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        public Pricebreaks[] PriceBreaks {
            get {
                return this.priceBreaksField;
            }
            set {
                this.priceBreaksField = value;
                this.RaisePropertyChanged("PriceBreaks");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ProductDetailUrl {
            get {
                return this.productDetailUrlField;
            }
            set {
                this.productDetailUrlField = value;
                this.RaisePropertyChanged("ProductDetailUrl");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool Reeling {
            get {
                return this.reelingField;
            }
            set {
                this.reelingField = value;
                this.RaisePropertyChanged("Reeling");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ROHSStatus {
            get {
                return this.rOHSStatusField;
            }
            set {
                this.rOHSStatusField = value;
                this.RaisePropertyChanged("ROHSStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string SuggestedReplacement {
            get {
                return this.suggestedReplacementField;
            }
            set {
                this.suggestedReplacementField = value;
                this.RaisePropertyChanged("SuggestedReplacement");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int MultiSimBlue {
            get {
                return this.multiSimBlueField;
            }
            set {
                this.multiSimBlueField = value;
                this.RaisePropertyChanged("MultiSimBlue");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public UnitWeightKg UnitWeightKg {
            get {
                return this.unitWeightKgField;
            }
            set {
                this.unitWeightKgField = value;
                this.RaisePropertyChanged("UnitWeightKg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.mouser.com/service")]
    public partial class ResultParts : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numberOfResultField;
        
        private MouserPart[] partsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int NumberOfResult {
            get {
                return this.numberOfResultField;
            }
            set {
                this.numberOfResultField = value;
                this.RaisePropertyChanged("NumberOfResult");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public MouserPart[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByKeyword", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByKeywordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.mouser.com/service")]
        public MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public string keyword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=1)]
        public int records;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=2)]
        public int startingRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string searchOptions;
        
        public SearchByKeywordRequest() {
        }
        
        public SearchByKeywordRequest(MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader, string keyword, int records, int startingRecord, string searchOptions) {
            this.MouserHeader = MouserHeader;
            this.keyword = keyword;
            this.records = records;
            this.startingRecord = startingRecord;
            this.searchOptions = searchOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByKeywordResponse", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByKeywordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public MikroPic.EdaTools.v1.MouserSearchApi.ResultParts SearchByKeywordResult;
        
        public SearchByKeywordResponse() {
        }
        
        public SearchByKeywordResponse(MikroPic.EdaTools.v1.MouserSearchApi.ResultParts SearchByKeywordResult) {
            this.SearchByKeywordResult = SearchByKeywordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByPartNumber", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByPartNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.mouser.com/service")]
        public MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public string mouserPartNumber;
        
        public SearchByPartNumberRequest() {
        }
        
        public SearchByPartNumberRequest(MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader, string mouserPartNumber) {
            this.MouserHeader = MouserHeader;
            this.mouserPartNumber = mouserPartNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchByPartNumberResponse", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class SearchByPartNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public MikroPic.EdaTools.v1.MouserSearchApi.ResultParts SearchByPartNumberResult;
        
        public SearchByPartNumberResponse() {
        }
        
        public SearchByPartNumberResponse(MikroPic.EdaTools.v1.MouserSearchApi.ResultParts SearchByPartNumberResult) {
            this.SearchByPartNumberResult = SearchByPartNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Calculator", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class CalculatorRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://api.mouser.com/service")]
        public MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public MikroPic.EdaTools.v1.MouserSearchApi.MCalculator calculatorParameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=1)]
        public int records;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=2)]
        public int startingRecord;
        
        public CalculatorRequest() {
        }
        
        public CalculatorRequest(MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader, MikroPic.EdaTools.v1.MouserSearchApi.MCalculator calculatorParameters, int records, int startingRecord) {
            this.MouserHeader = MouserHeader;
            this.calculatorParameters = calculatorParameters;
            this.records = records;
            this.startingRecord = startingRecord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculatorResponse", WrapperNamespace="http://api.mouser.com/service", IsWrapped=true)]
    public partial class CalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.mouser.com/service", Order=0)]
        public MikroPic.EdaTools.v1.MouserSearchApi.ResultParts CalculatorResult;
        
        public CalculatorResponse() {
        }
        
        public CalculatorResponse(MikroPic.EdaTools.v1.MouserSearchApi.ResultParts CalculatorResult) {
            this.CalculatorResult = CalculatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchAPISoapChannel : MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchAPISoapClient : System.ServiceModel.ClientBase<MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap>, MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap {
        
        public SearchAPISoapClient() {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordResponse MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap.SearchByKeyword(MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordRequest request) {
            return base.Channel.SearchByKeyword(request);
        }
        
        public MikroPic.EdaTools.v1.MouserSearchApi.ResultParts SearchByKeyword(MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader, string keyword, int records, int startingRecord, string searchOptions) {
            MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordRequest inValue = new MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.keyword = keyword;
            inValue.records = records;
            inValue.startingRecord = startingRecord;
            inValue.searchOptions = searchOptions;
            MikroPic.EdaTools.v1.MouserSearchApi.SearchByKeywordResponse retVal = ((MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap)(this)).SearchByKeyword(inValue);
            return retVal.SearchByKeywordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberResponse MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap.SearchByPartNumber(MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberRequest request) {
            return base.Channel.SearchByPartNumber(request);
        }
        
        public MikroPic.EdaTools.v1.MouserSearchApi.ResultParts SearchByPartNumber(MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader, string mouserPartNumber) {
            MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberRequest inValue = new MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.mouserPartNumber = mouserPartNumber;
            MikroPic.EdaTools.v1.MouserSearchApi.SearchByPartNumberResponse retVal = ((MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap)(this)).SearchByPartNumber(inValue);
            return retVal.SearchByPartNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MikroPic.EdaTools.v1.MouserSearchApi.CalculatorResponse MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap.Calculator(MikroPic.EdaTools.v1.MouserSearchApi.CalculatorRequest request) {
            return base.Channel.Calculator(request);
        }
        
        public MikroPic.EdaTools.v1.MouserSearchApi.ResultParts Calculator(MikroPic.EdaTools.v1.MouserSearchApi.MouserHeader MouserHeader, MikroPic.EdaTools.v1.MouserSearchApi.MCalculator calculatorParameters, int records, int startingRecord) {
            MikroPic.EdaTools.v1.MouserSearchApi.CalculatorRequest inValue = new MikroPic.EdaTools.v1.MouserSearchApi.CalculatorRequest();
            inValue.MouserHeader = MouserHeader;
            inValue.calculatorParameters = calculatorParameters;
            inValue.records = records;
            inValue.startingRecord = startingRecord;
            MikroPic.EdaTools.v1.MouserSearchApi.CalculatorResponse retVal = ((MikroPic.EdaTools.v1.MouserSearchApi.SearchAPISoap)(this)).Calculator(inValue);
            return retVal.CalculatorResult;
        }
        
        public bool ServiceStatus() {
            return base.Channel.ServiceStatus();
        }
    }
}
